 <br><div class="primary">
    <button type="submit"  class="action save primary" id="Pablo_address_edit_submit" title="Pablo_check_delivery_zone">
        <span><?php echo __('Check Delivery Zone') ?></span>
    </button>
    <button type="submit"  style="display: none" class="action save primary" id="Pablo_address_save_submit" title="Pablo_save_address_button">
           <span><?php echo __('Save Address') ?></span>
    </button>
    <br>
</div>
<div class="Pablo_deliveryzones  zx-row">
     <div id="map_init" class="php_var" ><?php echo $block->helper->mapInit(); ?></div>
    <div id="Pablo_code_mode" class="php_var">address_edit</div>
    <div id="Pablo_out_zone" class="php_var"><?php echo $block->getOutZoneContent(); ?> </div>
    <div id="Pablo_fail_zone" class="php_var"><?php echo $block->getFailZoneContent(); ?> </div>
    <div class="zx-col-md-8">
        <div id="delivery_map"></div>
    </div>
    <div id="Pablo_deliveryzones_data_result" class="zx-col-md-4 " >
        <div id="Pablo_deliveryzones_data_result_div" style="visibility: hidden;">
            <div><br></div>
            <div class="result-label"><?php echo __('Zone') ?>:</div><div id="zone_name" class="result-data"></div>
            <div class="result-label"><?php echo __('Section') ?>:</div><div id="section_name" class="result-data"></div>
            <hr class="result-line" >
            <div class="result-label"><?php echo __('Delivery ') ?>:</div><div id="section_delivery_data" class="result-data"></div>
            <hr class="result-line" >
            <div class="result-label"><?php echo __('Distance to Facility (by road)') ?>:</div><div id="distanceText" class="result-data"></div>
            <hr class="result-line" >
            <div class="result-label"><?php echo __('Delivery Cost: €') ?></div><div id="section_dly_cost" class="result-data"></div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
{
     "*": {
            "Pablo_DeliveryZones/js/address_edit": {  }

           }
      }
</script>
